# Generated by Django 2.2.3 on 2020-04-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headline',
            new_name='Story',
        ),
    ]
